# Generated by Django 5.2.7 on 2025-10-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, default='No description yet', null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.CharField(choices=[('action', '⚔️ Action'), ('adventure', '🗺️ Adventure'), ('comedy', '😂 Comedy'), ('drama', '🎭 Drama'), ('fantasy', '🧙\u200d♂️ Fantasy'), ('horror', '👻 Horror'), ('mystery', '🕵️ Mystery'), ('romance', '❤️ Romance'), ('sci-fi', '🚀 Sci-Fi'), ('slice_of_life', '☕ Slice of Life'), ('sports', '🏀 Sports'), ('supernatural', '👽 Supernatural'), ('thriller', ' 🕷️ Thriller'), ('mecha', '🤖 Mecha'), ('historical', '🏰 Historical')], default='action', max_length=50),
        ),
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='poster',
            field=models.ImageField(upload_to='anime_posters/'),
        ),
    ]
