# Generated by Django 5.2.7 on 2025-10-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_anime_description_anime_genre_anime_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.CharField(default='action', max_length=100),
        ),
    ]
