# Generated by Django 5.2.7 on 2025-10-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_anime_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.CharField(default='Action', max_length=100),
        ),
        migrations.AlterField(
            model_name='anime',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='anime_posters/'),
        ),
    ]
