# Generated by Django 5.2.7 on 2025-10-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_rating_anime_global_rating_alter_post_auther_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='anime',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
