# Generated by Django 5.2.7 on 2025-11-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_anime_publisher_alter_animefavorit_anime_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='animefavorit',
            unique_together={('user', 'anime')},
        ),
        migrations.AlterUniqueTogether(
            name='postfavorit',
            unique_together={('user', 'post')},
        ),
    ]
