# Generated by Django 5.2.7 on 2025-11-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_contact_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-11-05 00:00'),
            preserve_default=False,
        ),
    ]
